"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓](#31363B)\
[ 󰣇 ](bg:#31363B fg:#EFF0F1)\
[](bg:#3DAEE9 fg:#31363B)\
$directory\
[](fg:#3DAEE9 bg:#2A2E32)\
$git_branch\
$git_status\
[](fg:#2A2E32 bg:#232629)\
$nodejs\
$bun\
$rust\
$golang\
$php\
[](fg:#232629 bg:#1B1E20)\
$time\
[ ](fg:#1B1E20)\
\n$character"""

[directory]
style = "fg:#EFF0F1 bg:#3DAEE9"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#2A2E32"
format = '[[ $symbol $branch ](fg:#3DAEE9 bg:#2A2E32)]($style)'

[git_status]
style = "bg:#2A2E32"
format = '[[($all_status$ahead_behind )](fg:#3DAEE9 bg:#2A2E32)]($style)'

[nodejs]
symbol = ""
style = "bg:#232629"
format = '[[ $symbol ($version) ](fg:#3DAEE9 bg:#232629)]($style)'

[bun]
symbol = ""
style = "bg:#232629"
format = '[[ $symbol ($version) ](fg:#3DAEE9 bg:#232629)]($style)'

[rust]
symbol = ""
style = "bg:#232629"
format = '[[ $symbol ($version) ](fg:#3DAEE9 bg:#232629)]($style)'

[golang]
symbol = ""
style = "bg:#232629"
format = '[[ $symbol ($version) ](fg:#3DAEE9 bg:#232629)]($style)'

[php]
symbol = ""
style = "bg:#232629"
format = '[[ $symbol ($version) ](fg:#3DAEE9 bg:#232629)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#1B1E20"
format = '[[  $time ](fg:#BDC3C7 bg:#1B1E20)]($style)'

[character]
success_symbol = "[❯](bold #3DAEE9)"
error_symbol = "[❯](bold #ED1515)"
